#!/bin/bash


# Run this script from the directory where it is located: ./debug.
# Prerequisites:
# Android SDK for Mac OS X.
# Apache Ant: port install apache-ant.


# Export environment variables to find the Android SDK and NDK tools.
export ANDROID_HOME=~/scr/android-sdk-macosx
export PATH=$PATH:~/scr/android-sdk-macosx/platform-tools:~/scr/android-sdk-macosx/tools:~/scr/android-ndk-r10e


# Clean binaries.
ant clean
EXIT_CODE=$?
if [ $EXIT_CODE != 0 ]; then
  exit
fi


# Create assets index.
# mkdir -p assets/external
# rsync -a jni/* assets/external
find assets -name ".deps" -exec rm -r "{}" \; > /dev/null 2>&1
find assets -name ".dirstamp" -delete
# ant createAssetIndexExternal


# Build source.
ant debug
EXIT_CODE=$?
if [ $EXIT_CODE != 0 ]; then
  exit
fi
